"""Add users and storage table

Revision ID: 41fac0f5de2f
Revises: 
Create Date: 2022-09-22 07:59:27.514420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "41fac0f5de2f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=True),
        sa.Column("email", sa.String(length=256), nullable=False),
        sa.Column("phone", sa.String(length=256), nullable=True),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("point", sa.Integer(), nullable=False),
        sa.Column("business_class", sa.String(length=256), nullable=True),
        sa.Column("business_name", sa.String(length=256), nullable=True),
        sa.Column("business_president", sa.String(length=256), nullable=True),
        sa.Column("is_notification", sa.Boolean(), nullable=True),
        sa.Column(
            "approve_status_flag",
            sa.Enum("W", "A", "D", "S", name="userapprovestatusflag"),
            nullable=True,
        ),
        sa.Column("is_superuser", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hashed_password", sa.String(length=256), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "storages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["storages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_storages_id"), "storages", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_storages_id"), table_name="storages")
    op.drop_table("storages")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
